package Domain.Catalog;

public class Person {
    private String fName;
    private String lName;
    private int phoneNumber;
    private int uID;

    public Person(String fName, String lName, int phoneNumber, int uID) {
        this.fName = fName;
        this.lName = lName;
        this.phoneNumber = phoneNumber;
        this.uID = uID; //TODO Should be generated by Database.
    }

    public String getfName() {
        return fName;
    }

    public void setfName(String fName) {
        this.fName = fName;
    }

    public String getlName() {
        return lName;
    }

    public void setlName(String lName) {
        this.lName = lName;
    }

    public int getPhoneNumber() {
        return phoneNumber;
    }

    public void setPhoneNumber(int phoneNumber) {
        this.phoneNumber = phoneNumber;
    }

    public int getuID() {
        return uID;
    }

    @Override
    public String toString() {
        return "Person{" +
                "fName='" + fName + '\'' +
                ", lName='" + lName + '\'' +
                ", phoneNumber=" + phoneNumber +
                ", uID=" + uID +
                '}' + "\n";
    }
}
