package Domain.Catalog;

public class Person {
    private String mail;
    private String fName;
    private String lName;
    private int phoneNumber;
    private int uID;
    private String description;



    public Person(String mail, String fName, String lName, int phoneNumber, int uID, String description) {
        this.mail = mail;
        this.fName = fName;
        this.lName = lName;
        this.phoneNumber = phoneNumber;
        this.uID = uID; //TODO Should be generated by Database.
        this.description = description;
    }

    public String getMail() {
        return mail;
    }
    public void setMail(){
        this.mail = mail;
    }
    public String getfName() {
        return fName;
    }

    public void setfName(String fName) {
        this.fName = fName;
    }

    public String getlName() {
        return lName;
    }

    public void setlName(String lName) {
        this.lName = lName;
    }

    public int getPhoneNumber() {
        return phoneNumber;
    }

    public void setPhoneNumber(int phoneNumber) {
        this.phoneNumber = phoneNumber;
    }

    public int getuID() {
        return uID;
    }

    public String getDescription(){
        return description;
    }

    public void setDescription(){
        this.description = description;
    }

    public void setMail(String mail) {
        this.mail = mail;
    }

    public void setDescription(String description) {
        this.description = description;
    }

    @Override
    public String toString() {
        return "Person{" +
                "fName='" + fName + '\'' +
                ", lName='" + lName + '\'' +
                ", phoneNumber=" + phoneNumber +
                ", uID=" + uID +
                '}' + "\n";
    }
}
