package Domain;

import Domain.Catalog.Catalog;
import Domain.Catalog.Production;
import Persistens.PersistanceHandler;

import java.util.Date;

public class Facade implements CreditManager {

    private PersistanceHandler persistanceHandler = PersistanceHandler.getInstance();
    private Catalog catalog;


    @Override
    public void ViewAllProductions() {
        throw new UnsupportedOperationException();
    }

    @Override
    public Production chooseProduction(int productionID) {
        return catalog.getProduction(productionID);
    }

    @Override
    public void addCredit(int personID, String jobtitle) {
    persistanceHandler.addCredit(personID, jobtitle);
    }

    @Override
    public void confirmChanges() {

    }

    /**         AddPerson: Is suppose to add a new person to the Database, then query the same person and add to catalog ( WITH the ID Generated by DB )
     *
     * @param mail
     * @param fname
     * @param lname
     * @param phonenumber
     * @param description
     *
     *
     */

    @Override
    public void addPerson(String mail, String fname, String lname, int phonenumber, String description) {
        if(persistanceHandler.addPerson(mail,fname,lname,phonenumber,description)){
            //TODO addPerson() method to Catalog, + list
            //TODO Make it add the person from database to Catalog.
        }
    }

    @Override
    public void findProduction() {

    }

    @Override
    public void generateReport(int productionID, Date releaseDate) {

    }

    @Override
    public void saveReport() {

    }
}
